#!/bin/bash

docker stop sb
docker rm sb
sudo -Rf ~/Desktop/sb/my-env/postgres/pgdata
docker build . -t sbpi

docker run -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=11qazxsw22 -p 5432:5432 --name sb -v ~/Desktop/sb/my-env/postgres/pgdata:/var/lib/postgresql/data/ -d sbpi

# docker run -d --hostname rabbitmq --name denarius-rabbit -v ~/Desktop/sb/my-env/rabbitmq:/var/lib/rabbitmq -v ~/Desktop/sb/my-env/docker/enabled_plugins:/etc/rabbitmq/enabled_plugins -e RABBITMQ_ERLANG_COOKIE=denarius -e RABBITMQ_DEFAULT_VHOST="/" -e RABBITMQ_DEFAULT_USER=rabbitmq -e RABBITMQ_DEFAULT_PASS=rabbitmq -p 15672:15672 -p 5672:5672 rabbitmq:3.7.14-management
